### ISSUE TITLE
Longer secrets doesn't work

### ISSUE THREAD

**Issue by Peronia** [oplik0/solo2-desktop#111]
Hi, I'am using Win 11 and app version 1.0.2 with a solokey v2. When I try to add longer secrets, like from Dropbox or Amazon and click save, nothing happens. When I remove chars it get saved but the TOTP is wrong (of course).

**Comment by oplik0** [comment]
The issue was padding - TOTP secrets are encoded as base32 strings, and the solo2-cli is using an implementation that requires the input to follow the spec when it comes to padding. So every string needs to be aligned to a multiple of 8 characters, with `=` at the end being used for padding.

It seems some services use secrets that aren't aligned, without the padding - so now the app will just add the padding if the secret is too short.
